# Generated by Django 4.0 on 2021-12-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20180227_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='path',
            field=models.CharField(default='/home/username/', max_length=50),
        ),
    ]
