---
kind: pipeline
type: exec
name: build-exec
platform:
  os: linux
  arch: arm
steps:
  - name: Install poetry
    commands:
      - apt-get update && apt-get install python3-venv 
  - name: install packages
    commands: 
      - curl -sSL https://install.python-poetry.org | python3 - 
 
triggers:
  branch:
  - master 
  event:
  - push
  - tag