---
kind: pipeline
type: exec
name: build-exec
platform:
  os: linux
  arch: arm
steps:
  - name: Install poetry
    commands:
      - apt-get update -y && apt-get install python3-venv -y 
  - name: create poetry home directory
    commands:
      - mkdir $HOME/poetry
  - name: install packages
    commands: 
      - curl -sSL https://install.python-poetry.org | python3 -  #POETRY_HOME=./.venv/poetryhome
  # - name: install packages locally 
  #   commands:
  #     - .venv/poetryhome/bin/poetry config experimental.new-installer false && .venv/poetryhome/bin/poetry config virtualenvs.path ".venv" && .venv/poetryhome/bin/poetry config cache-dir .venv/.cache/ --local && .venv/poetryhome/bin/poetry config virtualenvs.create true --local
  - name: install django packages
    commands:
      - $HOME/poetry/bin/poetry install 
  - name: Django initilization
    commands:
      - $HOME/poetry/bin/poetry run python manage.py test 
 
triggers:
  branch:
  - master 
  - dronetest
  event:
  - push
  - tag