---
kind: pipeline
type: docker
name: build-exec
platform:
  os: linux
  arch: arm
steps:
  - name: Install poetry
    commands:
      - apt-get update -y && apt-get install python3-venv -y 
      - mkdir $HOME/poetry
      - curl -sSL https://install.python-poetry.org |  POETRY_HOME="/etc/poetry" python3 - 
      - /etc/poetry/bin/poetry config experimental.new-installer false && /etc/poetry/bin/poetry config virtualenvs.path ".venv" && /etc/poetry/bin/poetry config cache-dir .venv/.cache/ --local && /etc/poetry/bin/poetry config virtualenvs.create true --local
      - /etc/poetry/bin/poetry install && ls -la ./ && ls -la  .venv && /etc/poetry/bin/poetry config --list
      - /etc/poetry/bin/poetry run python manage.py test 
 
triggers:
  branch:
  - master 
  - dronetest
  event:
  - push
  - tag