---
kind: pipeline
type: docker
name: build-exec
platform:
  os: linux
  arch: arm
steps:
  - name: Install poetry
    image: python:3.7
    commands:
      - apt-get update -y && apt-get install python3-venv curl -y 
      - mkdir $HOME/poetry
      - curl -sSL https://install.python-poetry.org |  python3 - 
      - ${HOME}/.poetry/bin/poetry config experimental.new-installer false && ${HOME}/.poetry/bin/poetry config virtualenvs.path ".venv" && ${HOME}/.poetry/bin/poetry config cache-dir .venv/.cache/ --local && ${HOME}/.poetry/bin/poetry config virtualenvs.create true --local
      - ${HOME}/.poetry/bin/poetry install && ls -la ./ && ls -la  .venv && ${HOME}/.poetry/bin/poetry config --list
      - ${HOME}/.poetry/bin/poetry run python manage.py test 
 

---
kind: pipeline
type: docker
name: test
platform:
  os: linux
  arch: arm
steps:
  - name: update
    image: debian
    commands:
      - apt-get update && apt-get install curl python3-venv python3 -y

triggers:
  branch:
  - master 
  - dronetest
  event:
  - push
  - tag
