---
kind: pipeline
type: exec
name: build-exec
platform:
  os: linux
  arch: arm
steps:
  - name: Install poetry
    commands:
      - apt-get update -y && apt-get install python3-venv -y 
  - name: install packages
    commands: 
      - curl -sSL https://install.python-poetry.org | python3 - 
  - name: install packages locally 
    commands:
      - poetry config virtualenvs.create true --local
  - name: install django packages
    commands:
      - poetry install
 
triggers:
  branch:
  - master 
  event:
  - push
  - tag