version: '3.9'

services:

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER="test"
  #     - POSTGRES_PASSWORD="TEST" 
  #     - POSTGRES_DB="cloudpanel"
  #   volumes:
  #     - .db-data:/var/lib/postgresql/data
  #   restart: always
  #   ports:
  #     - "5432:5432"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - '8000'
    # network_mode: "host"
    # depends_on:
    #   - db