[tool.poetry]
name = "cloud-management-panel"
version = "0.1.0"
description = ""
authors = ["Safa Bayar <rectionxx@gmail.com>"]

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "3.7"
Django = "^3.2"
psycopg2_binary = "2.8.5"
paramiko = "2.7.1"
=======
python = "^3.9"
Django = "^4.0.4"
psycopg2 = "^2.8.5"
psycopg2_binary = "^2.8.5"
paramiko = "^2.7.1"

>>>>>>> 0421e4450aeb637344bc8b053ecc07f0ca898bbb
urllib3 = "^1.26.7"
tzdata = "^2021.5"
sqlparse = "^0.4.2"
pycparser = "^2.21"

[tool.poetry.dev-dependencies]
requests = "2.25.0"
pytest = "^6.2.5"
cryptography = "^36.0.0"
cffi = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "piwheels"
url = "https://piwheels.org/simple/" 