version: '3.9'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER="test"
      - POSTGRES_PASSWORD="TEST" 
      - POSTGRES_DB="cloudpanel"
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      - ./dockerenv/db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"


  web:
    build: .
    command:  python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db