version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=TEST 
      - POSTGRES_DB=cloudpanel
    ports:
      - "5432:5432"
